spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: ${URL_DATABASE}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    database: POSTGRESQL
    hibernate:
        ddl-auto: create-drop
  server:
    port: ${PORT}
  jackson:
    serialization:
      write-dates-as-timestamps: false
